config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # devise_for :users
  root to: 'orders_to_products#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do

  end

  resources :orders_to_products, only: [:new, :update, :destroy]
  resources :orders, only: [ :show, :update]
  post 'orders_to_products/new' => 'orders_to_products#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/box.rb
class Box < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orders_to_products, dependent: :destroy
end

app/models/order_to_product.rb
class OrderToProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, :unit_price, presence: true
end

app/models/orders_to_products.rb
class OrdersToProducts < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders, through: :ordersToProduct
  validates :name, presence: true
  validates :width, presence: true
  validates :height, presence: true
  validates :depth, presence: true
  validates :weight_grams, presence: true


  validates :stock, presence: true, numericality: { only_integer: true }

    # has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    # if @order.status == 'open'
      @myproducts = OrdersToProducts.where(order_id:@order.id)
    # end
  end

  def update
    @order = Order.find(params[:id])
    redirect_to user_path(current_user) if @order.update(order_params)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/orders_to_product_controller.rb
class OrdersToProductController < ApplicationController
  def create

    @orders_to_product = OrdersToProduct.new(orders_to_product_params)
    @orders_to_product.save

    # flash[:notice] = "Successfully added to cart. #{view_context.link_to 'wanna see your cart?', order_path(@orders_to_product.order_id)}".html_safe
    # redirect_to @orders_to_product.product

    # redirect_to @orders_to_product.product, notice: "Succesfully added to cart"
  end

  def update
  end

  def destroy
    @product_in_order = OrdersToProduct.find(params[:id])
    @product_in_order.destroy
    redirect_to order_path(@product_in_order.order_id)
  end

  private

  def orders_to_product_params
    params.require(:orders_to_product).permit(:quantity, :product_id)
  end
end

app/controllers/orders_to_products_controller.rb
class OrdersToProductsController < ApplicationController

  def show
    @orders = Order.all
    @orders_to_product = OrdersToProducts.all
    @products = Product.all
  end

  def new
    @order = OrdersToProducts.new
    @products = Product.all
  end

  def create

    # "product"=>"1", "quantity"=>"2"
    @product = Product.find(params["order"]["product"])
    quantity = params["order"]["quantity"]
    @order = Order.new()
    @order.save!

    @orders_to_product = OrdersToProducts.new(quantity: quantity, product_id: @product.id, order_id: @order.id)
    @orders_to_product.save!
    # @order = Order.new()

    # @products = OrdersToProducts.product
    box = GettingBoxService.get(@order, [@orders_to_product], [@product])

    @order.box_id = box.id
    @order.save!
    # flash[:notice] = "Successfully added to cart. #{view_context.link_to 'wanna see your cart?', order_path(@orders_to_product.order_id)}".html_safe
    # redirect_to @orders_to_product.product

    # redirect_to @orders_to_product.product, notice: "Succesfully added to cart"
  end

  def update
  end

  def destroy
    @product_in_order = OrdersToProducts.find(params[:id])
    @product_in_order.destroy
    redirect_to order_path(@product_in_order.order_id)
  end

  # private

  # def orders_to_product_params
  #   params.require(:orders_to_products).permit!
  # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
        @products = Veeqo::Product.all
        puts @products

    end

    def show
        # Piece of code to show how to clean the data
        # @products = Veeqo::Product.all
        # myproducts = @products
        #@products[2].as_json
        # myproducts[2].sellables[0][:measurement_attributes]
        #     #that returns to me  {:width=>10.0, :height=>10.0, :depth=>15.0, id:=>52647189, :dimensions_unit=>"cm"}

        #getting the specific product
        @product = Veeqo::Product.find(@product.id)
        #id for reference 25999333 Veeqo::Product.find(25999333)
        mylistofattr = Array.new()

        @product.sellables.map{|items| mylistofattr << [ items[:measurement_attributes], :weight_grams => items[:weight_grams], :weight_unit => items[:weight_unit], :weight => items[:weight]]}

        #creating a single hash with my data organized
        mylistofattr = mylistofattr.flatten.inject(:merge)

    end

    def new
        @product = Product.new
      end

    def create
        @product = Product.new(product_params)
        if @product.save!
            redirect_to product_path(@product)
        else
            render :new
        end
    end

    def edit
    end

    def update
      @product.update(product_params)
      # redirect_to
    end

    def destroy
      @product.destroy product_path(@product)
    end

    private

    def set_product
      @product = Product.find(params[:id])
      authorize @product
    end

    def product_params
      params.require(:product).permit(:name, :description, :stock, :price, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/orders_to_product_helper.rb
module OrdersToProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VeeqoApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/show.html.erb
<div class="orders-container">
  <div class="form-centralize-review">
    <div class="heading-rounded-sm">
      <h2 style="text-align: center;"> My Order</h2>
    </div>
    <div class="form-borders-cart">

      <% if @myproducts %>

        <table class="styled-table">
          <thead >
            <tr class="table-title">
              <th scope="col col-pro layout-inline" >Product</th>
              <th scope="qty qty-plus">Quantity</th>
              <th scope="col col-price col-numeric">Unit Price</th>
              <th scope="col col-price col-numeric">Width</th>
              <th scope="col col-price col-numeric">Height</th>
              <th scope="col col-price col-numeric">Depth</th>
              <th scope="col col-price col-numeric">Stock</th>
              <th scope="col col-vat col-numeric">Partial</th>
            </tr>

          </thead>
            <tbody>
              <% sum = 0  %>
              <% @myproducts.each do |product| %>
                <tr>
                  <th scope='row'><%= Product.find(product.product_id).name %></th>
                  <td> <%=  product.quantity  %></td>
                  <td>$ <%=  product.unit_price %></td>
                  <td><%=  product.product.width %></td>
                  <td><%=  product.product.height %></td>
                  <td><%=  product.product.depth %></td>
                  <td><%=  product.product.stock %></td>
                  <td> <% sum += (product.quantity) * (product.unit_price) %> $ <%=  (product.quantity) * (product.unit_price) %> <%= link_to orders_to_product_path(product),
                  method: 'DELETE' , remote:true do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
        </table>
        <hr>
        <p><strong>Total Price : $ <%= sum %></strong></p>
      <div class="btn-box">
        <%= link_to 'Close', root_path, class: "order-btn"%>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/orders_to_product/show.html.erb
<%= link_to "go back to products", products_path %>
<h2>Name: <%= @product.name%></h2>
<p>Price: <%= @product.price  %></p>

<% @orders.each do |order| %>
  <%= order.product.name %>
<% end %>

<%# link to seller's profile %>
<% @product.review.each do |review| %>
  <% sum_of_ratings += review.rating %>
<% end %>
<% if @product.review.count == 0 %>
  <p> This product has not been reviewed <p>
<% else %>
  <p>Average Rating: <%= "#{sum_of_ratings/@product.review.count} Reviews made: #{@product.review.count}" %></p>
<% end %>

app/views/orders_to_products/new.html.erb
<div class="container main-container ">
<div class="logo">
    <%= image_tag "logo.png", height: 50, width: 50, crop: :fill, class: 'empty card-trip-img' %>
  </div>
<h1 class="center">Beep Box </h1>
<p class="center">Find the best box for you!</p>
  <div class="row justify-content-center my-3">
    <div class="col-6 ">
      <%= simple_form_for :order  do |f| %>
      <div class="form-group">
        <label for="exampleFormControlSelect1">Product</label>
        <!-- <select class="form-control" id="exampleFormControlSelect1">
          <% @products.each do |product| %>
            <option> <%= product.name%> </option>
          <% end %>
        </select> -->
        <%= f.input :product, collection: @products, label: false  %>
        <div>
          <span>Quantity </span>
          <%= f.input :quantity, label: false %>
        </div>
      </div>
      <%= link_to root_path do %>
        <%= f.button :submit, class: "btn btn-flat"%>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/orders_to_products/show.html.erb
<div class="main-container">
  <div class="logo">
    <%= image_tag "logo.png", height: 50, width: 50, crop: :fill, class: 'empty card-trip-img' %>
  </div>
  <div class="orders-container mt-3">
    <div class="container order-details">
      <div class="form-centralize-review d-flex flex-column align-items-center">
        <div class="heading-rounded-sm">
          <h2 style="text-align: center;"> Order and Package</h2>
        </div>
        <table class="styled-table">
          <thead>
            <tr class="table-title">
              <th scope="col">Order</th>
              <th scope="col">Order List</th>
              <th scope="col">Quanity list</th>
              <th scope="col">Package size</th>
            </tr>
          </thead>
          <tbody>
            <% @orders_to_product.each do |order_to_product| %>
            <tr>
              <td>
                <%= link_to "#{Order.find(order_to_product.order_id).id}", order_path((Order.find(order_to_product.order_id).id))%>
              </td>
              <td><%= @products.find(order_to_product.product_id).name %></td>
              <td><%= order_to_product.quantity %> </td>
              <td><%= Box.find(Order.find(order_to_product.order_id).box_id).name %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
        <div class="btn-box">
        <%= link_to "new order", new_orders_to_product_path, class: "order-btn" %>
        </div>
      </div>
    </div>
  </div>

</div>